import { GoogleGenerativeAI, SchemaType } from '@google/generative-ai';
import dotenv from 'dotenv';

dotenv.config();

const genAI = new GoogleGenerativeAI(process.env.GEMINI_API_KEY);

const analysisSchema = {
  type: SchemaType.ARRAY,
  description: "An array of localized disease analysis objects. Must contain exactly 4 objects for English, Hindi, Telugu, and Tamil.",
  items: {
    type: SchemaType.OBJECT,
    properties: {
      language: {
        type: SchemaType.STRING,
        description: "The language of this analysis object. Must be one of: English, Hindi, Telugu, Tamil.",
      },
      predictedDisease: {
        type: SchemaType.STRING,
        description: "The most likely medical condition or disease predicted based on the prescription and medicines.",
      },
      confidence: {
        type: SchemaType.STRING,
        description: "Confidence level of the prediction (e.g., High, Medium, Low) along with a short percentage if applicable.",
      },
      reason: {
        type: SchemaType.STRING,
        description: "Reason for this prediction based on the evidence.",
      },
      symptoms: {
        type: SchemaType.ARRAY,
        items: { type: SchemaType.STRING },
        description: "Symptoms commonly associated with the predicted disease.",
      },
      medicineRelationship: {
        type: SchemaType.ARRAY,
        items: {
          type: SchemaType.OBJECT,
          properties: {
            medicineName: { type: SchemaType.STRING },
            explanation: { type: SchemaType.STRING, description: "How this medicine contributes to the treatment." },
          },
          required: ["medicineName", "explanation"]
        },
      },
      dietRecommendation: {
        type: SchemaType.OBJECT,
        properties: {
          foodsToEat: { type: SchemaType.ARRAY, items: { type: SchemaType.STRING } },
          foodsToAvoid: { type: SchemaType.ARRAY, items: { type: SchemaType.STRING } },
          recommendedFruits: { type: SchemaType.ARRAY, items: { type: SchemaType.STRING } },
          recommendedVegetables: { type: SchemaType.ARRAY, items: { type: SchemaType.STRING } },
          recommendedDrinks: { type: SchemaType.ARRAY, items: { type: SchemaType.STRING } },
        },
        required: ["foodsToEat", "foodsToAvoid", "recommendedFruits", "recommendedVegetables", "recommendedDrinks"]
      },
      lifestyleRecommendation: {
        type: SchemaType.OBJECT,
        properties: {
          dailyRoutine: { type: SchemaType.STRING },
          exerciseSuggestions: { type: SchemaType.STRING },
          waterIntake: { type: SchemaType.STRING },
          sleepRecommendation: { type: SchemaType.STRING },
          homeCareTips: { type: SchemaType.ARRAY, items: { type: SchemaType.STRING } },
          generalWellness: { type: SchemaType.STRING },
        },
        required: ["dailyRoutine", "exerciseSuggestions", "waterIntake", "sleepRecommendation", "homeCareTips", "generalWellness"]
      },
      recoveryAdvice: {
        type: SchemaType.STRING,
      },
      disclaimer: {
        type: SchemaType.STRING,
        description: "Mandatory disclaimer in the respective language. English: 'This information is generated by AI based on the prescription and is intended for educational purposes only. It is not a confirmed medical diagnosis or treatment plan. Please consult a qualified healthcare professional before making any medical decisions.'"
      }
    },
    required: [
      "language", "predictedDisease", "confidence", "reason", "symptoms", 
      "medicineRelationship", "dietRecommendation", "lifestyleRecommendation", 
      "recoveryAdvice", "disclaimer"
    ]
  }
};

export const generateDiseaseAnalysis = async (prescriptionData, medicineData) => {
  try {
    const model = genAI.getGenerativeModel({
      model: 'gemini-3-flash-preview',
      generationConfig: {
        responseMimeType: "application/json",
        responseSchema: analysisSchema,
        temperature: 0.2, // Low temperature for more deterministic/factual generation
      }
    });

    const prompt = `
      You are an expert Medical AI Assistant. 
      Your task is to analyze the provided prescription and medicine data to predict the underlying disease, explain the treatment, and recommend a personalized diet and lifestyle plan.
      
      You must provide the output strictly matching the JSON schema.
      You MUST provide exactly 4 localized versions of the analysis in the array: 'English', 'Hindi', 'Telugu', and 'Tamil'. Ensure the translation is accurate and patient-friendly.
      
      Prescription Data:
      ${JSON.stringify(prescriptionData, null, 2)}
      
      Medicines Information from Database:
      ${JSON.stringify(medicineData, null, 2)}
      
      Generate the multi-lingual analysis array now.
    `;

    const result = await model.generateContent(prompt);
    const response = await result.response;
    const text = response.text();
    
    const parsed = JSON.parse(text);
    return parsed;
  } catch (error) {
    console.error('Gemini Analysis Service Error:', error);
    throw new Error('Failed to generate disease analysis from AI');
  }
};

const genericSchema = {
  type: SchemaType.OBJECT,
  properties: {
    targetMedicine: {
      type: SchemaType.OBJECT,
      properties: {
        medicineName: { type: SchemaType.STRING },
        composition: { type: SchemaType.STRING },
        manufacturer: { type: SchemaType.STRING },
        price: { type: SchemaType.NUMBER },
      },
      required: ["medicineName", "composition", "manufacturer", "price"]
    },
    alternatives: {
      type: SchemaType.ARRAY,
      items: {
        type: SchemaType.OBJECT,
        properties: {
          medicineName: { type: SchemaType.STRING },
          composition: { type: SchemaType.STRING },
          manufacturer: { type: SchemaType.STRING },
          price: { type: SchemaType.NUMBER },
          comparison: {
            type: SchemaType.OBJECT,
            properties: {
              brandPrice: { type: SchemaType.NUMBER },
              genericPrice: { type: SchemaType.NUMBER },
              savings: { type: SchemaType.NUMBER },
              savingsPercentage: { type: SchemaType.NUMBER },
            },
            required: ["brandPrice", "genericPrice", "savings", "savingsPercentage"]
          },
          _id: { type: SchemaType.STRING }
        },
        required: ["medicineName", "composition", "manufacturer", "price", "comparison", "_id"]
      }
    }
  },
  required: ["targetMedicine", "alternatives"]
};

export const generateGenericAlternatives = async (medicineName) => {
  try {
    const model = genAI.getGenerativeModel({
      model: 'gemini-3-flash-preview',
      generationConfig: {
        responseMimeType: "application/json",
        responseSchema: genericSchema,
        temperature: 0.3,
      }
    });

    const prompt = `
      You are an expert pharmacist AI. 
      The user searched for the branded medicine "${medicineName}".
      Provide its typical chemical composition, generic name, a typical Indian price (in INR), and a reputable manufacturer.
      Then, generate 8 real medicine alternatives available in India that have the EXACT same chemical composition. 
      Critically: Include an equal mix of exactly 4 popular premium branded medicines and 4 cheaper generic alternatives.
      Generate random realistic MongoDB ObjectIds for the _id fields in alternatives.
      Do not hallucinate the generics - use real Indian generic alternatives if possible, or highly plausible ones.
      Return the output strictly matching the JSON schema.
    `;

    const result = await model.generateContent(prompt);
    const text = result.response.text();
    return JSON.parse(text);
  } catch (error) {
    console.error('Gemini Generics Service Error:', error);
    throw new Error('Failed to generate generic alternatives from AI');
  }
};

const foodSafetySchema = {
  type: SchemaType.OBJECT,
  properties: {
    foodIdentified: { type: SchemaType.STRING },
    verdict: { type: SchemaType.STRING, description: "Must be 'Eat', 'Avoid', or 'Moderation'" },
    reasoning: { 
      type: SchemaType.ARRAY, 
      items: { type: SchemaType.STRING },
      description: "Creative, engaging, and detailed bullet points explaining why it's safe or dangerous based on their specific medical condition and active medicines." 
    }
  },
  required: ["foodIdentified", "verdict", "reasoning"]
};

export const analyzeFoodSafety = async (imageBase64, mimeType, medicalContext) => {
  try {
    const model = genAI.getGenerativeModel({
      model: 'gemini-3-flash-preview',
      generationConfig: {
        responseMimeType: "application/json",
        responseSchema: foodSafetySchema,
        temperature: 0.4,
      }
    });

    const prompt = `
      You are an expert, friendly, and highly creative Medical AI Dietitian.
      The user has uploaded an image of a food or meal they are about to eat.
      
      Here is their medical context (their active diseases and active medicines):
      ${medicalContext || 'No specific medical context provided. Provide general health advice.'}
      
      Identify the food in the image with an enthusiastic tone.
      Analyze whether it is safe for the user to consume this food based strictly on their medical context.
      Provide the reasoning as a list of distinct, creative, and medically accurate bullet points. 
      Return the output matching the JSON schema. Verdict must be "Eat", "Avoid", or "Moderation".
    `;

    const imagePart = {
      inlineData: {
        data: imageBase64,
        mimeType: mimeType
      }
    };

    const result = await model.generateContent([prompt, imagePart]);
    const text = result.response.text();
    return JSON.parse(text);
  } catch (error) {
    console.error('Gemini Food Safety Service Error:', error);
    throw new Error('Failed to analyze food safety from AI');
  }
};

