import mongoose from 'mongoose';

const localizedAnalysisSchema = mongoose.Schema({
  language: {
    type: String,
    enum: ['English', 'Hindi', 'Telugu', 'Tamil'],
    required: true,
  },
  predictedDisease: { type: String, required: true },
  confidence: { type: String, required: true },
  reason: { type: String, required: true },
  symptoms: [{ type: String }],
  medicineRelationship: [
    {
      medicineName: { type: String },
      explanation: { type: String },
    },
  ],
  dietRecommendation: {
    foodsToEat: [{ type: String }],
    foodsToAvoid: [{ type: String }],
    recommendedFruits: [{ type: String }],
    recommendedVegetables: [{ type: String }],
    recommendedDrinks: [{ type: String }],
  },
  lifestyleRecommendation: {
    dailyRoutine: { type: String },
    exerciseSuggestions: { type: String },
    waterIntake: { type: String },
    sleepRecommendation: { type: String },
    homeCareTips: [{ type: String }],
    generalWellness: { type: String },
  },
  recoveryAdvice: { type: String },
  disclaimer: {
    type: String,
    default: "This information is generated by AI based on the prescription and is intended for educational purposes only. It is not a confirmed medical diagnosis or treatment plan. Please consult a qualified healthcare professional before making any medical decisions.",
  },
});

const diseaseAnalysisSchema = mongoose.Schema(
  {
    prescription: {
      type: mongoose.Schema.Types.ObjectId,
      required: true,
      ref: 'Prescription',
      unique: true, // One analysis per prescription for now
    },
    analyses: [localizedAnalysisSchema],
  },
  {
    timestamps: true,
  }
);

const DiseaseAnalysis = mongoose.model('DiseaseAnalysis', diseaseAnalysisSchema);

export default DiseaseAnalysis;
